import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ListCustomers from '../components/listCustomers'

export default function Home() {


  // const newTodo = await API.graphql({ query: mutations.createCustomer, variables: {input: todoDetails}});
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ListCustomers />
      <main className={styles.main}>
       <ul>
         <li>Add auth</li>
         <li>Confirm Auth works</li>
         <li>Add styles to make it look good</li>
         <li>Add form for info</li>
         <li>Add backend middleware</li>
       </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
